// V2 · Phase 9C — Print-friendly artifacts. PDF-style 8.5×11 letter renders.
// These are the auditor-grade documents the system produces. Tenant-downloadable
// from My Documents, AM-bundleable into audit packs.

const PAGE = {
  width: 816,   // 8.5in × 96dpi
  height: 1056, // 11in × 96dpi
  margin: 56,   // ~0.6in
};

// Page chrome — letterhead + footer for every artifact
function PrintPage({ title, docNum, children }) {
  return (
    <div style={{
      width: PAGE.width, minHeight: PAGE.height, background: '#FFFFFF',
      padding: PAGE.margin, position: 'relative',
      fontFamily: HF.body, color: HF.ink,
      boxShadow: '0 4px 24px rgba(31,26,18,0.15)',
      margin: '20px auto',
    }}>
      {/* Letterhead */}
      <div style={{
        display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between',
        paddingBottom: 14, borderBottom: `2px solid ${HF.accent}`,
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
          <div style={{
            width: 36, height: 36, borderRadius: HF.r.sm, background: HF.accent, color: HF.paper,
            display: 'grid', placeItems: 'center', fontFamily: HF.display, fontWeight: 800, fontSize: 17,
          }}>U</div>
          <div>
            <div style={{ fontFamily: HF.display, fontWeight: 800, fontSize: 16, letterSpacing: '-0.01em' }}>
              Universal Housing
            </div>
            <P size={10} color={HF.ink3}>
              Operated by Global Property Management Group · Las Vegas
            </P>
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <Eyebrow color={HF.ink3}>Document #</Eyebrow>
          <P size={11} weight={700} style={{ fontFamily: HF.mono, marginTop: 2 }}>{docNum}</P>
        </div>
      </div>

      <div style={{ marginTop: 20 }}>
        <Eyebrow>{title}</Eyebrow>
      </div>

      <div style={{ marginTop: 8 }}>{children}</div>

      {/* Footer pinned at bottom of page area */}
      <div style={{
        position: 'absolute', left: PAGE.margin, right: PAGE.margin, bottom: PAGE.margin / 2,
        paddingTop: 10, borderTop: `1px solid ${HF.border}`,
        display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
      }}>
        <P size={9} color={HF.ink3}>
          Generated by Universal Housing · audit trail attached
        </P>
        <P size={9} color={HF.ink3}>
          Page 1 of 1 · Confidential
        </P>
      </div>
    </div>
  );
}

// ── 9C.1 Lease PDF preview ───────────────────────────────────────────
function V2LeasePDF() {
  return (
    <PrintPage title="Residential Lease Agreement · Section 42 LIHTC" docNum="LSE-26-9341">
      <H1 style={{ fontSize: 24, marginTop: 4 }}>Juan Garcia Garden Apartments</H1>
      <P size={11} color={HF.ink3}>2851 Sunrise Ave · Las Vegas, NV 89101 · (725) 735-7779</P>

      <div style={{
        marginTop: 18, padding: 16, borderRadius: HF.r.sm,
        background: HF.cream, border: `1px solid ${HF.border}`,
      }}>
        <div style={{ display: 'grid', gridTemplateColumns: '160px 1fr', rowGap: 6, columnGap: 12 }}>
          {[
            ['Tenant', 'Marisol R. Cabrera'],
            ['Co-occupant', 'Sofia Cabrera (minor · age 14)'],
            ['Unit', '2BR · Unit 214 · 905 sq ft'],
            ['Building', 'A, second floor, greenery view'],
            ['Monthly rent', '$964.00 (Section 42 LIHTC cap)'],
            ['Utility allowance', '$0.00 (resident pays NV Energy + Southwest Gas)'],
            ['Security deposit', '$400.00'],
            ['Term', '12 months'],
            ['Effective', 'July 15, 2026 — July 14, 2027'],
            ['Rent due', '1st of each month · grace period to 5th'],
            ['Late fee', '$50 day 6 + $10/day thereafter (NRS 40.253 referenced)'],
            ['Auto-pay', 'Recommended · $10/mo rent discount when active'],
          ].map((row, i) => (
            <React.Fragment key={i}>
              <P size={10} color={HF.ink3} weight={600} style={{ textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                {row[0]}
              </P>
              <P size={11} weight={600}>{row[1]}</P>
            </React.Fragment>
          ))}
        </div>
      </div>

      <div style={{ marginTop: 20 }}>
        <Eyebrow color={HF.ink3}>Required addenda (signed via DocuSign)</Eyebrow>
        <div style={{ marginTop: 8 }}>
          {[
            { l: 'Community Policies & Procedures Addendum', s: 'DS-26-4488-A' },
            { l: 'Section 42 LIHTC Addendum', s: 'DS-26-4488-B' },
            { l: 'VAWA Lease Addendum (HUD-91067)', s: 'DS-26-4488-C' },
            { l: 'Drug-Free Housing Addendum', s: 'DS-26-4488-D' },
            { l: 'Crime-Free Lease Addendum', s: 'DS-26-4488-E' },
            { l: 'Smoke Detector Agreement', s: 'DS-26-4488-F' },
            { l: 'Lead-Based Paint Disclosure (pre-1978 property)', s: 'DS-26-4488-G' },
            { l: 'Resident Rules Acknowledgment', s: 'DS-26-4488-H' },
          ].map((a, i) => (
            <div key={i} style={{
              display: 'grid', gridTemplateColumns: '24px 1fr auto auto', gap: 10,
              padding: '6px 0', borderBottom: `1px dotted ${HF.border}`,
              alignItems: 'center',
            }}>
              <div style={{
                width: 18, height: 18, borderRadius: HF.r.pill, background: HF.ok,
                display: 'grid', placeItems: 'center',
              }}>
                <Icon name="check" size={11} color={HF.paper} />
              </div>
              <P size={11}>{a.l}</P>
              <P size={9} color={HF.ink3} style={{ fontFamily: HF.mono }}>{a.s}</P>
              <P size={10} color={HF.ok} weight={700}>Signed Jul 8, 2026</P>
            </div>
          ))}
        </div>
      </div>

      <div style={{
        marginTop: 26, paddingTop: 16, borderTop: `1px solid ${HF.border}`,
        display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 30,
      }}>
        <div>
          <Eyebrow color={HF.ink3}>Tenant signature</Eyebrow>
          <div style={{
            height: 50, marginTop: 8, borderBottom: `1.5px solid ${HF.ink}`,
            display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between',
            paddingBottom: 4,
          }}>
            <span style={{ fontFamily: '"Caveat", cursive', fontSize: 24, color: HF.accent }}>
              Marisol R. Cabrera
            </span>
          </div>
          <P size={10} color={HF.ink3} style={{ marginTop: 4 }}>
            DocuSign verified · Jul 8, 2026 · 11:24 AM PDT · IP 47.144.18.x
          </P>
        </div>
        <div>
          <Eyebrow color={HF.ink3}>PM signature</Eyebrow>
          <div style={{
            height: 50, marginTop: 8, borderBottom: `1.5px solid ${HF.ink}`,
            display: 'flex', alignItems: 'flex-end', paddingBottom: 4,
          }}>
            <span style={{ fontFamily: '"Caveat", cursive', fontSize: 24, color: HF.accent }}>
              Frank Hawkins
            </span>
          </div>
          <P size={10} color={HF.ink3} style={{ marginTop: 4 }}>
            DocuSign verified · Jul 8, 2026 · 11:38 AM PDT · IP 64.227.42.x
          </P>
        </div>
      </div>
    </PrintPage>
  );
}

// ── 9C.2 Application fee receipt ─────────────────────────────────────
function V2FeeReceipt() {
  return (
    <PrintPage title="Application Fee · Receipt" docNum="RCP-26-9341">
      <div style={{ display: 'flex', alignItems: 'baseline', justifyContent: 'space-between' }}>
        <div>
          <H1 style={{ fontSize: 22, marginTop: 4 }}>Application fee received</H1>
          <P size={11} color={HF.ink3}>
            Non-refundable · funds credit, employment & background checks
          </P>
        </div>
        <Tag tone="ok" style={{ padding: '4px 10px', fontSize: 12 }}>
          ✓ Paid · May 14, 2026
        </Tag>
      </div>

      <div style={{
        marginTop: 24, padding: 20, borderRadius: HF.r.md,
        border: `2px solid ${HF.accent}`, background: HF.accentLo,
      }}>
        <Eyebrow color={HF.accent}>Total paid</Eyebrow>
        <div style={{ fontFamily: HF.display, fontWeight: 800, fontSize: 44, color: HF.accent, letterSpacing: '-0.02em', marginTop: 4 }}>
          $71.90
        </div>
        <div style={{
          marginTop: 12, paddingTop: 12, borderTop: `1px dashed ${HF.accent}`,
          display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12,
        }}>
          <div>
            <Eyebrow color={HF.ink3}>Calculation</Eyebrow>
            <P size={12} style={{ marginTop: 4 }}>$35.95 × 1 adult HH member</P>
          </div>
          <div>
            <Eyebrow color={HF.ink3}>Plus minor children</Eyebrow>
            <P size={12} style={{ marginTop: 4 }}>1 minor · no fee</P>
          </div>
        </div>
      </div>

      <div style={{
        marginTop: 24, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16,
      }}>
        <div>
          <Eyebrow color={HF.ink3}>Applicant</Eyebrow>
          <P size={12} weight={700} style={{ marginTop: 4 }}>Marisol R. Cabrera</P>
          <P size={11} color={HF.ink3}>1408 E Charleston Blvd, Apt 6</P>
          <P size={11} color={HF.ink3}>Las Vegas, NV 89104</P>
        </div>
        <div>
          <Eyebrow color={HF.ink3}>Applied to</Eyebrow>
          <P size={12} weight={700} style={{ marginTop: 4 }}>Juan Garcia Garden Apts</P>
          <P size={11} color={HF.ink3}>2851 Sunrise Ave, Las Vegas NV 89101</P>
          <P size={11} color={HF.ink3}>2BR · Family · waitlist position #12</P>
        </div>
      </div>

      <div style={{ marginTop: 24 }}>
        <Eyebrow color={HF.ink3}>Payment details</Eyebrow>
        <div style={{
          marginTop: 8, padding: '12px 14px', borderRadius: HF.r.sm,
          background: HF.cream, border: `1px solid ${HF.border}`,
          display: 'grid', gridTemplateColumns: '140px 1fr', rowGap: 5, columnGap: 12,
        }}>
          {[
            ['Method', 'Debit card · VISA •••• 4242'],
            ['Processor', 'Heartland · PCI-DSS encrypted'],
            ['Transaction ID', 'HRT-2026-05-14-9341-A8C2'],
            ['Authorization', 'AUTH 481297'],
            ['Date / time', 'May 14, 2026 · 9:14 AM PDT'],
            ['Application #', 'APP-26-9341'],
          ].map((row, i) => (
            <React.Fragment key={i}>
              <P size={10} color={HF.ink3} weight={600} style={{ textTransform: 'uppercase', letterSpacing: '0.05em' }}>{row[0]}</P>
              <P size={11} style={{ fontFamily: row[0] === 'Method' || row[0] === 'Date / time' ? HF.body : HF.mono }}>{row[1]}</P>
            </React.Fragment>
          ))}
        </div>
      </div>

      <div style={{
        marginTop: 22, padding: '14px 16px', borderRadius: HF.r.sm,
        background: HF.sageLo, border: `1px solid #D2DDC9`,
      }}>
        <Eyebrow color={HF.sage}>Refund policy</Eyebrow>
        <P size={11} color={HF.ink2} style={{ marginTop: 6, lineHeight: 1.5 }}>
          The application fee is non-refundable per GPMGLV policy. If your application is
          withdrawn before document review begins, contact your Property Manager within 48 hours
          to request a partial refund. Auto-pay enrollment after move-in recaptures $10/month
          (~7 months to break even).
        </P>
      </div>
    </PrintPage>
  );
}

// ── 9C.3 Calc tape audit trail ───────────────────────────────────────
function V2CalcAuditTrail() {
  return (
    <PrintPage title="HUD-50059 Calculator Tape · Audit Trail" docNum="CT-26-9341">
      <H1 style={{ fontSize: 22, marginTop: 4 }}>Rent determination · Marisol R. Cabrera</H1>
      <P size={11} color={HF.ink3}>
        Section 42 LIHTC · Juan Garcia Garden Apts · Unit 214 · 2BR · effective Jul 15, 2026
      </P>

      <div style={{
        marginTop: 16, padding: '8px 14px', borderRadius: HF.r.sm,
        background: HF.okLo, border: `1px solid #CFE1CB`,
        display: 'flex', alignItems: 'center', gap: 8,
      }}>
        <Icon name="check" size={14} color={HF.ok} />
        <P size={11} color={HF.ok} weight={700}>
          Verified by Frank Hawkins on Jul 6, 2026 · 8 / 8 fields approved
        </P>
      </div>

      <div style={{ marginTop: 18 }}>
        <Eyebrow color={HF.ink3}>Part B · Annual income</Eyebrow>
        <table style={{ width: '100%', marginTop: 8, borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: HF.cream, borderBottom: `1px solid ${HF.border}` }}>
              {['Line', 'Source document', 'Extracted value', 'Conf.', 'Amount'].map(h => (
                <th key={h} style={{
                  padding: '6px 10px', textAlign: 'left',
                  fontFamily: HF.body, fontSize: 9, fontWeight: 700, color: HF.ink3,
                  textTransform: 'uppercase', letterSpacing: '0.05em',
                }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {[
              ['1', 'Pay stub #3 · LVUSD · May 9, 2026 (page 1)', 'Annualized from $1,645 biweekly', '96%', '$42,800.00'],
              ['2', '—', 'No SSA · pension documents', '100%', '$0.00'],
              ['3', 'Tax return Schedule C · 2025', 'No business income', '100%', '$0.00'],
              ['4', 'Bank stmt · Wells Fargo · May 2026', 'Interest earned (annualized)', '88%', '$48.00'],
            ].map((row, i) => (
              <tr key={i} style={{ borderBottom: `1px solid ${HF.border}` }}>
                <td style={{ padding: '6px 10px', fontFamily: HF.mono, fontSize: 11 }}>{row[0]}</td>
                <td style={{ padding: '6px 10px', fontSize: 11 }}>{row[1]}</td>
                <td style={{ padding: '6px 10px', fontSize: 11, color: HF.ink3 }}>{row[2]}</td>
                <td style={{ padding: '6px 10px', fontSize: 11, fontFamily: HF.mono, fontWeight: 700, color: parseInt(row[3]) > 90 ? HF.ok : HF.warn }}>{row[3]}</td>
                <td style={{ padding: '6px 10px', fontSize: 11, fontFamily: HF.display, fontWeight: 700, textAlign: 'right' }}>{row[4]}</td>
              </tr>
            ))}
            <tr style={{ background: HF.cream }}>
              <td colSpan="4" style={{ padding: '8px 10px', fontSize: 11, fontWeight: 700 }}>Total annual income</td>
              <td style={{ padding: '8px 10px', fontSize: 13, fontFamily: HF.display, fontWeight: 800, textAlign: 'right' }}>$42,848.00</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div style={{ marginTop: 18 }}>
        <Eyebrow color={HF.ink3}>Part C · Deductions (HUD 4350.3 Ch. 5-10)</Eyebrow>
        <table style={{ width: '100%', marginTop: 8, borderCollapse: 'collapse' }}>
          <tbody>
            {[
              ['Dependent · Sofia Cabrera (age 14)', '$480 × 1', '$480.00'],
              ['Child care', 'None reported', '$0.00'],
              ['Medical (elderly/disabled only)', 'N/A · under 62, not disabled', '$0.00'],
              ['Elderly/disabled family', 'N/A', '$0.00'],
            ].map((row, i) => (
              <tr key={i} style={{ borderBottom: `1px dotted ${HF.border}` }}>
                <td style={{ padding: '5px 10px', fontSize: 11 }}>{row[0]}</td>
                <td style={{ padding: '5px 10px', fontSize: 11, color: HF.ink3 }}>{row[1]}</td>
                <td style={{ padding: '5px 10px', fontSize: 11, fontFamily: HF.display, fontWeight: 700, textAlign: 'right' }}>{row[2]}</td>
              </tr>
            ))}
            <tr style={{ background: HF.cream }}>
              <td colSpan="2" style={{ padding: '8px 10px', fontSize: 11, fontWeight: 700 }}>Total deductions</td>
              <td style={{ padding: '8px 10px', fontSize: 13, fontFamily: HF.display, fontWeight: 800, textAlign: 'right' }}>$480.00</td>
            </tr>
          </tbody>
        </table>
      </div>

      <div style={{
        marginTop: 18, padding: 14, borderRadius: HF.r.sm,
        background: HF.sageLo, border: `1px solid #D2DDC9`,
      }}>
        <Eyebrow color={HF.sage}>Total tenant payment (HUD 4350.3 Ch. 5-25)</Eyebrow>
        <div style={{ marginTop: 6, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
          <P size={11}>30% × adjusted ÷ 12 = <b>$1,059.20</b></P>
          <P size={11}>10% × gross ÷ 12 = <b>$357.07</b></P>
        </div>
        <P size={11} style={{ marginTop: 8 }}>
          Greater of: <b>$1,059.20/mo</b>
        </P>
        <P size={11} style={{ marginTop: 4 }}>
          Section 42 LIHTC cap (2BR · 60% AMI · Juan Garcia): <b>$964.00/mo</b>
        </P>
        <div style={{
          marginTop: 8, padding: '8px 12px', borderRadius: HF.r.sm,
          background: HF.paper, border: `2px solid ${HF.sage}`,
          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        }}>
          <P size={11} weight={700}>Final monthly rent</P>
          <span style={{ fontFamily: HF.display, fontWeight: 800, fontSize: 20, color: HF.sage }}>
            $964.00
          </span>
        </div>
        <P size={10} color={HF.ink3} style={{ marginTop: 6 }}>
          Capped at LIHTC cap · the greater-of result exceeded the program max.
        </P>
      </div>
    </PrintPage>
  );
}

// ── 9C.4 Deposit disposition statement ───────────────────────────────
function V2DepositStatement() {
  return (
    <PrintPage title="Security Deposit Disposition · NRS 118A.242" docNum="DEP-27-3392">
      <H1 style={{ fontSize: 22, marginTop: 4 }}>Deposit refund statement</H1>
      <P size={11} color={HF.ink3}>
        Issued per NRS 118A.242 · within 21 days of move-out (Jun 30, 2027)
      </P>

      <div style={{
        marginTop: 20, padding: 16, borderRadius: HF.r.md,
        background: HF.okLo, border: `2px solid ${HF.ok}`,
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
      }}>
        <div>
          <Eyebrow color={HF.ok}>Refund amount</Eyebrow>
          <div style={{ fontFamily: HF.display, fontWeight: 800, fontSize: 38, color: HF.ok, letterSpacing: '-0.02em' }}>
            $400.00
          </div>
          <P size={11} color={HF.ink3}>Paid by ACH · arrives Jul 10–14, 2027</P>
        </div>
        <Tag tone="ok" style={{ padding: '6px 12px', fontSize: 12 }}>Full refund · zero deductions</Tag>
      </div>

      <div style={{
        marginTop: 22, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16,
      }}>
        <div>
          <Eyebrow color={HF.ink3}>Tenant</Eyebrow>
          <P size={12} weight={700} style={{ marginTop: 4 }}>Marisol R. Cabrera</P>
          <P size={11} color={HF.ink3}>Former unit: Juan Garcia · 214</P>
          <P size={11} color={HF.ink3}>Forwarding: 4421 N Tonopah Dr</P>
          <P size={11} color={HF.ink3}>Las Vegas, NV 89108</P>
        </div>
        <div>
          <Eyebrow color={HF.ink3}>Tenancy</Eyebrow>
          <P size={12} weight={700} style={{ marginTop: 4 }}>Jul 15, 2026 – Jun 30, 2027</P>
          <P size={11} color={HF.ink3}>11 months, 15 days</P>
          <P size={11} color={HF.ink3}>On-time payment record · 12/12</P>
          <P size={11} color={HF.ink3}>No outstanding work orders</P>
        </div>
      </div>

      <div style={{ marginTop: 22 }}>
        <Eyebrow color={HF.ink3}>Itemized statement</Eyebrow>
        <table style={{ width: '100%', marginTop: 8, borderCollapse: 'collapse' }}>
          <thead>
            <tr style={{ background: HF.cream, borderBottom: `1px solid ${HF.border}` }}>
              {['Item', 'Notes', 'Amount'].map(h => (
                <th key={h} style={{
                  padding: '6px 10px', textAlign: 'left',
                  fontFamily: HF.body, fontSize: 9, fontWeight: 700, color: HF.ink3,
                  textTransform: 'uppercase', letterSpacing: '0.05em',
                }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {[
              ['Original security deposit', 'Collected at move-in · Jul 15, 2026', '$400.00', 'pos'],
              ['Cleaning charges', 'Unit returned in good condition', '$0.00'],
              ['Damage repairs', 'No damage beyond normal wear', '$0.00'],
              ['Unpaid rent / fees', 'Account paid in full through Jun 30', '$0.00'],
              ['Replacement keys / locks', 'All keys + mailbox key returned', '$0.00'],
              ['Painting', 'No charge', '$0.00'],
              ['Debris removal', 'Unit was empty at walkthrough', '$0.00'],
            ].map((row, i) => (
              <tr key={i} style={{ borderBottom: `1px solid ${HF.border}` }}>
                <td style={{ padding: '7px 10px', fontSize: 11, fontWeight: 600 }}>{row[0]}</td>
                <td style={{ padding: '7px 10px', fontSize: 11, color: HF.ink3 }}>{row[1]}</td>
                <td style={{
                  padding: '7px 10px', fontSize: 12, fontFamily: HF.display, fontWeight: 700,
                  textAlign: 'right', color: row[3] === 'pos' ? HF.ok : HF.ink2,
                }}>{row[3] === 'pos' ? '+' : '−'} {row[2].replace('$','$')}</td>
              </tr>
            ))}
            <tr style={{ background: HF.okLo, borderTop: `2px solid ${HF.ok}` }}>
              <td colSpan="2" style={{ padding: '10px', fontSize: 12, fontWeight: 700, color: HF.ok }}>Net refund</td>
              <td style={{ padding: '10px', fontSize: 16, fontFamily: HF.display, fontWeight: 800, textAlign: 'right', color: HF.ok }}>
                $400.00
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <div style={{ marginTop: 20 }}>
        <Eyebrow color={HF.ink3}>Walkthrough condition comparison</Eyebrow>
        <table style={{ width: '100%', marginTop: 8, borderCollapse: 'collapse' }}>
          <tbody>
            {[
              ['Living room', 'Good', 'Good', '—'],
              ['Kitchen / appliances', 'Good', 'Good', '—'],
              ['Bedroom 1', 'Good', 'Good', '—'],
              ['Bedroom 2', 'Good', 'Good', '—'],
              ['Bathroom', 'Good', 'Good', '—'],
              ['Carpets / floors', 'Good', 'Good', '—'],
              ['Doors / windows / locks', 'Good', 'Good', '—'],
              ['Smoke + CO detectors', 'Tested OK', 'Tested OK', '—'],
            ].map((row, i) => (
              <tr key={i} style={{ borderBottom: `1px dotted ${HF.border}` }}>
                <td style={{ padding: '5px 10px', fontSize: 11, fontWeight: 600 }}>{row[0]}</td>
                <td style={{ padding: '5px 10px', fontSize: 10, color: HF.ink3 }}>Move-in: <b>{row[1]}</b></td>
                <td style={{ padding: '5px 10px', fontSize: 10, color: HF.ok }}>Move-out: <b>{row[2]}</b></td>
                <td style={{ padding: '5px 10px', fontSize: 11, textAlign: 'center' }}>
                  <Icon name="check" size={11} color={HF.ok} />
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <P size={10} color={HF.ink3} style={{ marginTop: 8 }}>
          Walkthrough conducted Jun 30, 2027 · 4:00 PM with Frank Hawkins, PM. Photo evidence
          attached (32 photos). Both parties signed digitally on completion.
        </P>
      </div>

      <div style={{
        marginTop: 22, padding: '12px 14px', borderRadius: HF.r.sm,
        background: HF.cream, border: `1px solid ${HF.border}`,
      }}>
        <P size={10} color={HF.ink3} style={{ lineHeight: 1.5 }}>
          <b>Your rights under NRS 118A:</b> You may dispute any charge within 30 days by
          contacting GPMGLV in writing. Free legal counsel is available through Nevada Legal
          Services at <b>(702) 386-1070</b>. This statement does not waive any claim you have
          against GPMGLV or any claim GPMGLV has against you.
        </P>
      </div>
    </PrintPage>
  );
}

Object.assign(window, { PrintPage, V2LeasePDF, V2FeeReceipt, V2CalcAuditTrail, V2DepositStatement });
