-- 2026-06-25 — seed the 10 GPM SENIOR communities into properties so
-- get_property_details answers address/amenities/pet-policy for them on a call.
-- Idempotent: INSERT only when the slug is not already present.

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Aldene Kline Senior Community','1327 H Street',NULL,'Las Vegas','NV','89106',0,'Las Vegas','(702) 920-6550','barlow@gpmglv.org','senior','["One & two-bedroom senior apartments", "Elevator access & ADA accommodations", "Community room with activities & programs", "Laundry facilities on site", "Secure entry & on-site management", "Walking distance to Lorenzi Park & shopping", "Near Valley Hospital & UMC", "RTC bus lines serving the neighborhood"]'::jsonb,NULL,'["ADA accommodations available", "Elevator access", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='aldene-kline-senior-community');

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Dr. Luther Mack, Jr. Senior Community','8158 Giles St.',NULL,'Las Vegas','NV','89123',0,'Las Vegas','(702) 920-6569',NULL,'senior','["Senior-focused apartment homes", "Community room and resident activities", "On-site laundry facilities", "Professional on-site management", "Secure entry and well-lit common areas", "Accessible routes and accommodations available", "Convenient access to transit and neighborhood services"]'::jsonb,NULL,'["Reasonable accommodations available upon request", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='dr-luther-mack-jr-senior-community');

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Dr. Paul Meacham Senior Community','65 E Windmill Ln',NULL,'Las Vegas','NV','89123',0,'Las Vegas','(877) 895-8207',NULL,'senior','["One & two-bedroom senior apartments", "Elevator access & ADA accommodations", "Community room with activities & programs", "Laundry facilities on site", "Secure entry & on-site management", "Close to shopping, dining & daily essentials", "Convenient access to nearby medical offices & services", "Transit access along Windmill and nearby major corridors"]'::jsonb,NULL,'["Reasonable accommodations available upon request", "ADA accommodations available", "Elevator access", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='dr-paul-meacham-senior-community');

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Ethel Mae Robinson Senior Apartments','1327 H Street',NULL,'Las Vegas','NV','89106',0,'Las Vegas','(702) 834-6565',NULL,'senior','["One & two-bedroom senior apartments", "Elevator access & ADA accommodations", "Community room with activities & programs", "Laundry facilities on site", "Secure entry & on-site management", "Close to groceries & neighborhood services", "Convenient access to nearby medical services", "RTC bus routes nearby"]'::jsonb,NULL,'["Reasonable accommodations available upon request", "ADA accommodations available", "Elevator access", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='ethel-mae-robinson-senior-apartments');

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Louise Shell Senior Apartments','2101 N. Martin Luther King Blvd.',NULL,'Las Vegas','NV','89106',0,'Las Vegas','(702) 646-4802',NULL,'senior','["One & two-bedroom senior apartments", "Elevator access & ADA accommodations", "Community room with activities & programs", "Laundry facilities on site", "Secure entry & on-site management", "Close to groceries & neighborhood services", "Convenient access to nearby medical services", "RTC bus routes along MLK Blvd and nearby corridors"]'::jsonb,NULL,'["Reasonable accommodations available upon request", "ADA accommodations available", "Elevator access", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='louise-shell-senior-apartments');

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Owens Senior Housing','1626 Davis Pl.',NULL,'North Las Vegas','NV','89030',0,'North Las Vegas','(702) 642-0896',NULL,'senior','["One & two-bedroom senior apartments", "Elevator access & ADA accommodations", "Community room with activities & programs", "Laundry facilities on site", "Secure entry & on-site management", "Close to groceries & neighborhood services", "Convenient access to nearby medical services", "Public transit access in Downtown North Las Vegas"]'::jsonb,NULL,'["Reasonable accommodations available upon request", "ADA accommodations available", "Elevator access", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='owens-senior-housing');

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Senator Harry Reid Senior Apartments','328 N. 11th Str.',NULL,'Las Vegas','NV','89101',0,'Las Vegas','(702) 383-1091',NULL,'senior','["One & two-bedroom senior apartments", "Elevator access & ADA accommodations", "Community room with activities & programs", "Laundry facilities on site", "Secure entry & on-site management", "Walking distance to groceries, parks & Fremont", "Near hospitals & healthcare providers", "RTC bus lines within 2 blocks"]'::jsonb,NULL,'["Reasonable accommodations available upon request", "ADA accommodations available", "Elevator access", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='senator-harry-reid-senior-apartments');

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Senator Richard Bryan Senior Apartments','2651 Searles Ave.',NULL,'Las Vegas','NV','89101',0,'Las Vegas','(702) 649-3508',NULL,'senior','["One & two-bedroom senior apartments", "Elevator access & ADA accommodations", "Community room with activities & programs", "Laundry facilities on site", "Secure entry & on-site management", "Close to groceries & neighborhood services", "Convenient access to nearby medical services", "Transit access in the surrounding downtown-east corridor"]'::jsonb,NULL,'["Reasonable accommodations available upon request", "ADA accommodations available", "Elevator access", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='senator-richard-bryan-senior-apartments');

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Smith Williams Senior Apartments','575 E. Lake Mead Pkwy.',NULL,'Henderson','NV','89015',0,'Henderson','(702) 382-3726',NULL,'senior','["Senior-focused apartment homes", "Community room and resident activities", "On-site laundry facilities", "Professional on-site management", "Secure entry and well-lit common areas", "Accessible routes and accommodations available", "Convenient access to transit and neighborhood services"]'::jsonb,NULL,'["Reasonable accommodations available upon request", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='smith-williams-senior-apartments');

INSERT INTO properties (name,address_line1,address_line2,city,state,zip,unit_count,ami_area,phone,email,property_type,amenities,pet_policy,accessibility,total_vacancy,waiting_list_enabled)
SELECT 'Yale Keyes Senior Apartments','1705 Yale Str.',NULL,'North Las Vegas','NV','89030',0,'North Las Vegas','(702) 642-7758',NULL,'senior','["Senior-focused apartment homes", "Community room and resident activities", "On-site laundry facilities", "Professional on-site management", "Secure entry and well-lit common areas", "Accessible routes and accommodations available", "Convenient access to transit and neighborhood services"]'::jsonb,NULL,'["Reasonable accommodations available upon request", "Equal Housing Opportunity"]'::jsonb,0,true
WHERE NOT EXISTS (SELECT 1 FROM properties WHERE trim(both '-' from regexp_replace(lower(name),'[^a-z0-9]+','-','g'))='yale-keyes-senior-apartments');

